### ISSUE TITLE
CSS framework decision

### ISSUE THREAD

**Issue by AlexStormwood** [AlexStormwood/feb23-t3w8-ptcg-app#5]
Choose one: 

Bootstrap
Material UI 
Bulma
Tailwind

**Comment by captainaomi** [comment]
Bootstrap's the only one I've heard of, so voting that ;)
Preferably would like the more popular one, so that I'm learning something useful in a world of options haha

**Comment by nate-0hz** [comment]
Tailwind so I can learn more about people's passionate stance on the subject, on social media.

**Comment by BuzSaliji** [comment]
Either Bootstrap or Tailwind!

**Comment by tatermysalad** [comment]
Bootstrap:
- Developed by Twitter.
- Provides a comprehensive set of pre-designed CSS and JavaScript components.
- Focuses on responsive web design.
- Offers a grid system, typography, and various UI components for building modern web applications.

Material UI:
- A CSS framework that implements Google's Material Design guidelines.
- Designed for creating applications with a Material Design aesthetic.
- Provides a range of pre-styled UI components, icons, and animations.
- Popular choice for building web applications with a sleek and consistent look.

Bulma:
- A lightweight and modern CSS framework based on Flexbox.
- Known for its simplicity and ease of use.
- Offers a responsive grid system and basic styling, leaving room for customization.
- Suitable for creating clean and minimalistic web designs.

Tailwind CSS:
- A utility-first CSS framework.
- Focuses on composing layouts and designs using utility classes.
- Highly customizable and flexible, allowing for rapid development.
- Gained popularity for its speed and efficiency in creating custom designs.

**Comment by katielock92** [comment]
> Bootstrap's the only one I've heard of, so voting that ;) Preferably would like the more popular one, so that I'm learning something useful in a world of options haha

What she said ^^

**Comment by AlexStormwood** [comment]
![image](https://github.com/AlexStormwood/feb23-t3w8-ptcg-app/assets/22165407/2d7abfc6-6a3f-45ea-ab94-8bb60e62f963)

Refer to this diagram for more info:

**Comment by e-mehegan** [comment]
Bootstrap is the one I hear most about and what I have seen mentioned a lot on job ads that I have seen too.

**Comment by JackDixon019** [comment]
Bootstrap so I can pull myself up

**Comment by hotteok219** [comment]
> Bootstrap:
> 
> * Developed by Twitter.
> * Provides a comprehensive set of pre-designed CSS and JavaScript components.
> * Focuses on responsive web design.
> * Offers a grid system, typography, and various UI components for building modern web applications.
> 
> Material UI:
> 
> * A CSS framework that implements Google's Material Design guidelines.
> * Designed for creating applications with a Material Design aesthetic.
> * Provides a range of pre-styled UI components, icons, and animations.
> * Popular choice for building web applications with a sleek and consistent look.
> 
> Bulma:
> 
> * A lightweight and modern CSS framework based on Flexbox.
> * Known for its simplicity and ease of use.
> * Offers a responsive grid system and basic styling, leaving room for customization.
> * Suitable for creating clean and minimalistic web designs.
> 
> Tailwind CSS:
> 
> * A utility-first CSS framework.
> * Focuses on composing layouts and designs using utility classes.
> * Highly customizable and flexible, allowing for rapid development.
> * Gained popularity for its speed and efficiency in creating custom designs.

Bootstrap for a Facey vs Twitter fight

**Comment by KirkWest** [comment]
yeah Bootstrap as well

**Comment by zakaryjs** [comment]
Bootstrap

**Comment by zMyrddin** [comment]
Tailwind because it sounds like a Pokemon move for a pokemon project

**Comment by tatermysalad** [comment]
Tailwind sounds nice for customisability in the future

**Comment by ellenpham** [comment]
one vote for Bootstrap 👍

**Comment by jordansbenjamin** [comment]
Tailwind!

**Comment by ZachHolmesDev** [comment]
Tailwind as i have heard having it in the HTML makes it easier to go back later plus speed of development apparently

**Comment by Looch8** [comment]
Either bootstrap or Tailwind

**Comment by kelshardy** [comment]
Voting Bootstrap 😎

**Comment by Limchiem** [comment]
Tailwind.

**Comment by AlexStormwood** [comment]
Bootstrap is most voted, we will do that!
